from pyhop_anytime import *
global state, goals
state = State('state')
state.calibration_target = Oset([('instrument0','star3'),('instrument1','groundstation0'),('instrument10','star2'),('instrument11','star3'),('instrument12','groundstation4'),('instrument13','star2'),('instrument14','star3'),('instrument15','groundstation4'),('instrument16','groundstation0'),('instrument17','groundstation4'),('instrument18','star3'),('instrument19','star2'),('instrument2','groundstation1'),('instrument20','groundstation4'),('instrument21','star2'),('instrument22','groundstation1'),('instrument3','groundstation4'),('instrument4','star3'),('instrument5','groundstation4'),('instrument6','groundstation1'),('instrument7','star3'),('instrument8','groundstation0'),('instrument9','star3')])
state.on_board = Oset([('instrument0','satellite0'),('instrument1','satellite0'),('instrument10','satellite4'),('instrument11','satellite5'),('instrument12','satellite5'),('instrument13','satellite5'),('instrument14','satellite6'),('instrument15','satellite6'),('instrument16','satellite6'),('instrument17','satellite7'),('instrument18','satellite7'),('instrument19','satellite8'),('instrument2','satellite0'),('instrument20','satellite8'),('instrument21','satellite8'),('instrument22','satellite9'),('instrument3','satellite1'),('instrument4','satellite1'),('instrument5','satellite1'),('instrument6','satellite2'),('instrument7','satellite3'),('instrument8','satellite4'),('instrument9','satellite4')])
state.pointing = Oset([('satellite0','star15'),('satellite1','planet10'),('satellite2','star24'),('satellite3','phenomenon9'),('satellite4','planet19'),('satellite5','planet10'),('satellite6','planet11'),('satellite7','planet11'),('satellite8','groundstation4'),('satellite9','planet11')])
state.power_avail = Oset(['satellite0','satellite1','satellite2','satellite3','satellite4','satellite5','satellite6','satellite7','satellite8','satellite9'])
state.supports = Oset([('instrument0','infrared4'),('instrument1','spectrograph3'),('instrument10','image0'),('instrument10','image2'),('instrument10','spectrograph3'),('instrument11','image0'),('instrument12','image0'),('instrument12','infrared4'),('instrument13','spectrograph3'),('instrument14','image0'),('instrument14','spectrograph3'),('instrument14','thermograph1'),('instrument15','image0'),('instrument15','image2'),('instrument15','thermograph1'),('instrument16','image2'),('instrument16','spectrograph3'),('instrument17','image0'),('instrument17','image2'),('instrument17','thermograph1'),('instrument18','image2'),('instrument18','thermograph1'),('instrument19','infrared4'),('instrument19','thermograph1'),('instrument2','image0'),('instrument2','image2'),('instrument2','thermograph1'),('instrument20','thermograph1'),('instrument21','thermograph1'),('instrument22','infrared4'),('instrument22','spectrograph3'),('instrument22','thermograph1'),('instrument3','image0'),('instrument3','thermograph1'),('instrument4','image2'),('instrument4','thermograph1'),('instrument5','image2'),('instrument5','spectrograph3'),('instrument5','thermograph1'),('instrument6','image0'),('instrument7','infrared4'),('instrument8','spectrograph3'),('instrument9','image0'),('instrument9','image2'),('instrument9','thermograph1')])
state.calibrated = Oset()
state.have_image = Oset()
state.power_on = Oset()

goals = State('goals')
goals.have_image = Oset([('phenomenon17','infrared4'),('phenomenon18','spectrograph3'),('phenomenon23','image0'),('phenomenon5','thermograph1'),('phenomenon9','image2'),('planet10','image0'),('planet11','infrared4'),('planet21','thermograph1'),('planet22','image2'),('planet6','infrared4'),('planet7','image0'),('planet8','thermograph1'),('star12','image0'),('star13','image0'),('star14','thermograph1'),('star15','image0'),('star16','thermograph1'),('star20','image0'),('star24','infrared4')])
goals.pointing = Oset([('satellite5','planet6'),('satellite7','star3'),('satellite8','star15'),('satellite9','star16')])

