from pyhop_anytime import *
global state, goals
state = State('state')
state.calibration_target = Oset([('instrument0','star2'),('instrument1','star4'),('instrument10','star4'),('instrument11','groundstation3'),('instrument12','groundstation3'),('instrument13','star4'),('instrument14','groundstation3'),('instrument15','star2'),('instrument16','star4'),('instrument17','star0'),('instrument18','groundstation1'),('instrument19','groundstation3'),('instrument2','star4'),('instrument20','groundstation1'),('instrument21','star2'),('instrument22','star4'),('instrument23','star2'),('instrument24','star2'),('instrument25','star2'),('instrument26','star4'),('instrument27','groundstation3'),('instrument28','groundstation1'),('instrument3','star0'),('instrument4','groundstation3'),('instrument5','groundstation3'),('instrument6','groundstation3'),('instrument7','groundstation1'),('instrument8','star2'),('instrument9','star4')])
state.on_board = Oset([('instrument0','satellite0'),('instrument1','satellite0'),('instrument10','satellite1'),('instrument11','satellite1'),('instrument12','satellite1'),('instrument13','satellite1'),('instrument14','satellite1'),('instrument15','satellite1'),('instrument16','satellite2'),('instrument17','satellite2'),('instrument18','satellite2'),('instrument19','satellite2'),('instrument2','satellite0'),('instrument20','satellite3'),('instrument21','satellite3'),('instrument22','satellite4'),('instrument23','satellite4'),('instrument24','satellite4'),('instrument25','satellite4'),('instrument26','satellite4'),('instrument27','satellite4'),('instrument28','satellite4'),('instrument3','satellite0'),('instrument4','satellite0'),('instrument5','satellite0'),('instrument6','satellite0'),('instrument7','satellite0'),('instrument8','satellite0'),('instrument9','satellite0')])
state.pointing = Oset([('satellite0','groundstation1'),('satellite1','phenomenon19'),('satellite2','phenomenon14'),('satellite3','star10'),('satellite4','star16')])
state.power_avail = Oset(['satellite0','satellite1','satellite2','satellite3','satellite4'])
state.supports = Oset([('instrument0','image3'),('instrument1','infrared9'),('instrument10','infrared1'),('instrument10','spectrograph6'),('instrument10','thermograph8'),('instrument11','image4'),('instrument11','infrared1'),('instrument11','thermograph7'),('instrument12','infrared5'),('instrument12','infrared9'),('instrument12','thermograph8'),('instrument13','image2'),('instrument13','infrared1'),('instrument14','image3'),('instrument15','thermograph7'),('instrument16','image2'),('instrument16','infrared9'),('instrument17','infrared5'),('instrument18','infrared9'),('instrument19','image2'),('instrument19','infrared5'),('instrument2','image2'),('instrument2','image4'),('instrument2','thermograph8'),('instrument20','image2'),('instrument20','image3'),('instrument20','image4'),('instrument21','image3'),('instrument21','infrared5'),('instrument21','thermograph8'),('instrument22','infrared5'),('instrument22','thermograph8'),('instrument23','image3'),('instrument23','thermograph8'),('instrument24','thermograph8'),('instrument25','infrared5'),('instrument26','image3'),('instrument27','image2'),('instrument27','infrared9'),('instrument28','image4'),('instrument28','spectrograph0'),('instrument28','thermograph7'),('instrument3','infrared9'),('instrument4','image3'),('instrument4','thermograph8'),('instrument5','image4'),('instrument5','infrared9'),('instrument6','infrared1'),('instrument7','spectrograph6'),('instrument7','thermograph8'),('instrument8','infrared9'),('instrument8','spectrograph0'),('instrument8','thermograph7'),('instrument9','thermograph7')])
state.calibrated = Oset()
state.have_image = Oset()
state.power_on = Oset()

goals = State('goals')
goals.have_image = Oset([('phenomenon12','image4'),('phenomenon14','thermograph7'),('phenomenon19','image2'),('phenomenon19','image4'),('phenomenon21','image2'),('phenomenon21','image4'),('phenomenon21','thermograph7'),('phenomenon5','image3'),('phenomenon5','spectrograph0'),('phenomenon5','thermograph8'),('phenomenon8','infrared5'),('phenomenon8','spectrograph6'),('phenomenon8','thermograph7'),('planet13','image2'),('planet13','infrared5'),('planet13','spectrograph6'),('planet15','image3'),('planet18','infrared5'),('planet18','infrared9'),('planet18','thermograph7'),('planet22','image2'),('planet22','spectrograph6'),('planet7','image2'),('planet7','infrared5'),('planet7','spectrograph6'),('planet9','spectrograph6'),('star10','spectrograph6'),('star11','image3'),('star11','image4'),('star11','thermograph7'),('star16','image3'),('star16','image4'),('star20','spectrograph0'),('star23','image2'),('star23','infrared9'),('star24','infrared5'),('star24','spectrograph6'),('star6','image3'),('star6','spectrograph0'),('star6','spectrograph6')])
goals.pointing = Oset([('satellite1','phenomenon19')])

